security.jwt.token.secret-key: my-secret-key

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://213.183.41.33:5432/tobaco
    username: admin@admin.com
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
